### ISSUE TITLE
Windows-Key blocked for other keyboard shortcuts

### ISSUE THREAD

**Issue by nwin** [linuxmint/mintmenu#98]
Any other shortcut involving the Windows-Key does not work any more if the menu is configured to show when <Super> is pressed. 

On the other Hand if the Mint menu is configured to use ctrl+super super-l can be configured via system settings and used to lock the screen.

**Comment by freed00m** [comment]
Yes, having Mint mate 17.1 and I can confirm, having Super_L set as mintMenu shortcut it will block any other super_L + <key> shortcut capabilities.

**Comment by sevenskull** [comment]
I can confirm this too!
On cinnamon, everything goes fine, but in mate the key you set for mintmenu, blocks every other global shortcut on mint using combination with this key.
For example: Super + E, for explorer is blocked when using Super for open mint menu.
Would be nice to fix this problem.

**Comment by dd23** [comment]
The Problem seems to be caused somewhere in those lines:
https://github.com/linuxmint/mintmenu/blob/master/usr/lib/linuxmint/mintMenu/keybinding.py#L158-L174
It seems to be the way how the key events are handled. Here's more [documentation on the Xlib Events](https://tronche.com/gui/x/xlib/input/XAllowEvents.html).

Changing `X.AsyncKeyboard` to `X.SyncKeyboard` *seems* to do the trick, but I'm not sure if that's correct at all!

I haven't worked with Xlib before, so I can't figure this one out, but maybe someone else might find this helpful.

**Comment by philipzae** [comment]
Yes i've faced the same problem and use Ctrl+Super for the menu, so i can use Super with other key combinations.

**Comment by UnoSD** [comment]
@dd23 Thank for the suggestion, now it doesn't pop up the menu when I press Super+something, but yet shortcuts are not working.

**Comment by anthony-cros** [comment]
http://superuser.com/a/889528/616364 was helpful to me (for MATE), I was able to remap the key to something else ("Menu" key in my case), and my "Windows" key shortcuts worked properly after that. I find that this binding not showing in the "Keyboard Shortcuts" menu is very unnerving!

**Comment by Zulgrib** [comment]
This problem is very annoying and is a waste of physical key and time.

**Comment by sevenskull** [comment]
This problem is still happening on Linux Mint 18 MATE.
I use cinnamon on my desktop (which everything works fine), and i want to use MATE or XFCE on my work notebook (performance issues), but i don't want to use different shortcuts everyday.
It would be amazing if i could do the same shortcuts on MATE or XFCE.

**Comment by monsta** [comment]
Ok, https://github.com/linuxmint/mintmenu/issues/172 fixes it, at least it works for me. Can you guys test it as well?

**Comment by sevenskull** [comment]
I am using Mint Mate 18.2 and it's not entirely fixed.
At first it seens fixed, but it's a little weird the behavior.
My mint version already has this fix, so i started to change some keybinds to feel more like cinnamon/windows.
Super: (Open menu: default behavior for mint mate)
Super + D: Show desktop [Worked]
Super + E: Home folder [didn't work]
Super + right arrow: Tile window to east (right) side of the screen [Worked]
Super + left arrow: Tile window to west (left) side of the screen [didn't work, and stopped Super + right arrow]
Super + F: Custom shortcut (caja) [didn't work]

If i change the shortcut for mate menu (Super) for another key, it start work every other shortcut with Super again.

So, for me, it just work flawlessly for "show desktop".

**Comment by Magissia** [comment]
The problem is not resolved here.
Mod4+E doesn't bring up file explorer like I have configured it.

**Comment by Zulgrib** [comment]
This issue is not resolved.

**Comment by UnoSD** [comment]
It is not working for me either, after an hack found in the comments I'm now able to get the shortcut by pressing it twice, but that sends also the letter keystroke and it is quite annoying to have to do it twice.

**Comment by adargu** [comment]
Still a problem here, too. (18.2)
I use GNOME Do with the shortcut "<Super>Space". (Left Win Key + Space)

When "Keyboard shortcut" in mintMenu (v5.8.2) is assigned to "Super_L" (Left Win Key) the GNOME Do shortcut doesn't work anymore.

When I assign mintMenu shortcut for example to "<Super>Shift_L"  (Left Win Key + Shift) the GNOME Do shortcut works again.

**Comment by forcecore** [comment]
Still a problem in 18.2 MATE edition of Mint. I had to change the shortcut key for the mint menu to Right Window key to get Mod4+{right arrow} or {left arrow} or Mod4+e combinations working.

**Comment by monsta** [comment]
Should be fixed now with mate-settings-daemon update to 1.18.2.

**Comment by adargu** [comment]
Version: 1.18.2-1+sonya

I'm able to use Mod4+{right arrow} or {left arrow} or Mod4+e in "Keyboard Shortcuts" preference configuration.

But  [this](https://github.com/linuxmint/mintmenu/issues/98#issuecomment-329767905) Problem with GNOME Do still exists.

When I assign mintMenu shortcut for example to "Shift_L" (Left Win Key + Shift) the GNOME Do works fine.

**Comment by UnoSD** [comment]
Is there an issue on mate-settings-daemon to track? (and possibly linked to a commit so we can patch old versions)
